set_property PACKAGE_PIN E3 [get_ports clk_in1]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in1]
set_property PACKAGE_PIN C12 [get_ports resetn]
set_property IOSTANDARD LVCMOS33 [get_ports resetn]

set_property PACKAGE_PIN C4 [get_ports UART_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_rxd]
set_property PACKAGE_PIN D4 [get_ports UART_txd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_txd]

set_property PACKAGE_PIN H17 [get_ports {LED_tri_o[0]}]
set_property PACKAGE_PIN K15 [get_ports {LED_tri_o[1]}]
set_property PACKAGE_PIN J13 [get_ports {LED_tri_o[2]}]
set_property PACKAGE_PIN N14 [get_ports {LED_tri_o[3]}]
set_property PACKAGE_PIN R18 [get_ports {LED_tri_o[4]}]
set_property PACKAGE_PIN V17 [get_ports {LED_tri_o[5]}]
set_property PACKAGE_PIN U17 [get_ports {LED_tri_o[6]}]
set_property PACKAGE_PIN U16 [get_ports {LED_tri_o[7]}]
set_property PACKAGE_PIN V16 [get_ports {LED_tri_o[8]}]
set_property PACKAGE_PIN T15 [get_ports {LED_tri_o[9]}]
set_property PACKAGE_PIN U14 [get_ports {LED_tri_o[10]}]
set_property PACKAGE_PIN T16 [get_ports {LED_tri_o[11]}]
set_property PACKAGE_PIN V15 [get_ports {LED_tri_o[12]}]
set_property PACKAGE_PIN V14 [get_ports {LED_tri_o[13]}]
set_property PACKAGE_PIN V12 [get_ports {LED_tri_o[14]}]
set_property PACKAGE_PIN V11 [get_ports {LED_tri_o[15]}]


set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[0]}]

set_property PACKAGE_PIN C9 [get_ports MDIO_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports MDIO_mdc]
set_property PACKAGE_PIN A9 [get_ports mdio_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports mdio_mdio_io]
set_property PACKAGE_PIN D5 [get_ports eth_ref_clk]
set_property IOSTANDARD LVCMOS33 [get_ports eth_ref_clk]
set_property PACKAGE_PIN D9 [get_ports RMII_PHY_M_crs_dv]
set_property IOSTANDARD LVCMOS33 [get_ports RMII_PHY_M_crs_dv]
set_property PACKAGE_PIN C10 [get_ports RMII_PHY_M_rx_er]
set_property IOSTANDARD LVCMOS33 [get_ports RMII_PHY_M_rx_er]
set_property PACKAGE_PIN B9 [get_ports RMII_PHY_M_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports RMII_PHY_M_tx_en]
set_property PACKAGE_PIN D10 [get_ports {RMII_PHY_M_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RMII_PHY_M_rxd[1]}]
set_property PACKAGE_PIN C11 [get_ports {RMII_PHY_M_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RMII_PHY_M_rxd[0]}]
set_property PACKAGE_PIN A8 [get_ports {RMII_PHY_M_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RMII_PHY_M_txd[1]}]
set_property PACKAGE_PIN A10 [get_ports {RMII_PHY_M_txd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RMII_PHY_M_txd[0]}]

set_property PACKAGE_PIN B3 [get_ports eth_phy_rstn]
set_property IOSTANDARD LVCMOS33 [get_ports eth_phy_rstn]

set_property PACKAGE_PIN C14 [get_ports i2c_scl]
set_property PACKAGE_PIN C15 [get_ports i2c_sda]
set_property IOSTANDARD LVCMOS33 [get_ports i2c_scl]
set_property IOSTANDARD LVCMOS33 [get_ports i2c_sda]

set_property PACKAGE_PIN U13 [get_ports {anodes[7]}]
set_property PACKAGE_PIN K2 [get_ports  {anodes[6]}]
set_property PACKAGE_PIN T14 [get_ports {anodes[5]}]
set_property PACKAGE_PIN P14 [get_ports {anodes[4]}]
set_property PACKAGE_PIN J14 [get_ports {anodes[3]}]
set_property PACKAGE_PIN T9 [get_ports  {anodes[2]}]
set_property PACKAGE_PIN J18 [get_ports {anodes[1]}]
set_property PACKAGE_PIN J17 [get_ports {anodes[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anodes[0]}]

set_property PACKAGE_PIN T10 [get_ports {seg[0]}]
set_property PACKAGE_PIN R10 [get_ports {seg[1]}]
set_property PACKAGE_PIN K16 [get_ports {seg[2]}]
set_property PACKAGE_PIN K13 [get_ports {seg[3]}]
set_property PACKAGE_PIN P15 [get_ports {seg[4]}]
set_property PACKAGE_PIN T11 [get_ports {seg[5]}]
set_property PACKAGE_PIN L18 [get_ports {seg[6]}]
set_property PACKAGE_PIN H15 [get_ports {seg[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]

#create_clock -name clock_in -period 10 [get_ports clk_in1]